'use strict';
const RAW={'9A':['Isabella','Martin','Lucia','Lucas','Matias','Alejandro','Samuel','David','Emilia','Maria Camila','Juana','Juliana','Pablo','Lorenzo','Juan Sebastian','Maria Jose','Mariana','Juan Jose','Sofia','Maria Del Rosario'],'9B':['Antonia','Elena','Samuel','Ana Lucia','Antonia','Santiago','Julieta','Gabriela','Jose Jacobo','Antonia','Mariana','Matías','Valentina','Juana','Salomon','Jacobo','Sofia','Jacobo','Tomas'],'9C':['Mariana','Sara Sofia','Juan Sebastián','Alejandro','Isabella','Jeronimo','Matias','Maria Adelaida','Belen','Isabella','Sara','Maria Antonia','Maria Jose','Juan Diego','Mariana','Pablo','Emmanuel','David','Catalina']};
const GROUPS=Object.fromEntries(Object.entries(RAW).map(([group,names])=>{const totals={},counts={};names.forEach(n=>totals[n]=(totals[n]||0)+1);return[group,names.map((name,i)=>({id:`${group}-${i+1}`,name,label:totals[name]>1?`${name} · ${counts[name]=(counts[name]||0)+1}`:name}))]}));
const POS=Array.from({length:20},(_,i)=>({x:[22,36,50,64,78][i%5],y:[29,43.5,58,72.5][Math.floor(i/5)]}));
const KEY='glm-grade9-hexagonal-seating-v1', $=id=>document.getElementById(id),blank=()=>Object.fromEntries(Object.keys(GROUPS).map(g=>[g,Array(20).fill(null)]));
let plans=blank(),group='9A',selected=null,dragged=null,touch=null,skipClick=false,toastTimer;
function validate(data){const source=data?.seats||data,result=blank();for(const g of Object.keys(GROUPS)){const seats=source?.[g],allowed=new Set(GROUPS[g].map(s=>s.id)),seen=new Set();if(!Array.isArray(seats)||seats.length!==20)throw Error(`Invalid desk list for ${g}`);result[g]=seats.map(id=>{if(id!==null&&(!allowed.has(id)||seen.has(id)))throw Error(`Invalid or repeated student in ${g}`);if(id)seen.add(id);return id})}return result}
try{const saved=localStorage.getItem(KEY);if(saved)plans=validate(JSON.parse(saved))}catch(e){console.warn('Unable to restore seating plan',e)}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000)}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,seats:plans}))}catch(e){toast('Browser storage unavailable; export a backup.')}}
function student(id){return GROUPS[group].find(s=>s.id===id)}
function seat(id){return plans[group].indexOf(id)}
function clearSelection(){selected=null;render()}
function put(id,index){if(!GROUPS[group].some(s=>s.id===id)||index<0||index>=20)return;const seats=plans[group],before=seats.indexOf(id),other=seats[index];if(before===index){clearSelection();return}if(before>=0)seats[before]=other||null;seats[index]=id;selected=null;save();render();toast(other?`${student(id).label} and ${student(other).label} swapped desks.`:`${student(id).label} assigned to desk ${index+1}.`)}
function remove(id){const index=seat(id);if(index<0)return;plans[group][index]=null;selected=null;save();render();toast('Student returned to the roster.')}
function deskClick(index){const id=plans[group][index];if(selected){if(selected===id)clearSelection();else put(selected,index)}else if(id){selected=id;render()}else toast('Select a student from the roster first.')}
function endDrag(){dragged=null;document.querySelectorAll('.drop-target').forEach(e=>e.classList.remove('drop-target'))}
function setupTouch(el,id){el.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||!e.isPrimary)return;touch={id,el,pointer:e.pointerId,x:e.clientX,y:e.clientY,moved:false,ghost:null}});el.addEventListener('pointermove',e=>{const d=touch;if(!d||d.el!==el||d.pointer!==e.pointerId)return;if(!d.moved&&Math.hypot(e.clientX-d.x,e.clientY-d.y)>9){d.moved=true;d.ghost=document.createElement('div');d.ghost.className='touch-ghost';d.ghost.textContent=student(id).label;document.body.append(d.ghost);el.setPointerCapture(e.pointerId)}if(d.moved){e.preventDefault();d.ghost.style.left=`${e.clientX+15}px`;d.ghost.style.top=`${e.clientY-20}px`;document.querySelectorAll('.drop-target').forEach(node=>node.classList.remove('drop-target'));document.elementFromPoint(e.clientX,e.clientY)?.closest('.desk')?.classList.add('drop-target')}},{passive:false});el.addEventListener('pointerup',e=>{const d=touch;if(!d||d.el!==el||d.pointer!==e.pointerId)return;if(d.moved){const target=document.elementFromPoint(e.clientX,e.clientY),dest=target?.closest('.desk');skipClick=true;if(dest)put(id,Number(dest.dataset.seat));else if(target?.closest('#roster')&&seat(id)>=0)remove(id);else render();setTimeout(()=>skipClick=false,0)}d.ghost?.remove();touch=null;endDrag()});el.addEventListener('pointercancel',()=>{touch?.ghost?.remove();touch=null;endDrag()})}
function renderDesks(){const root=$('desks');root.replaceChildren();plans[group].forEach((id,i)=>{const pos=POS[i],person=id?student(id):null,b=document.createElement('button');b.type='button';b.className=`desk${id?' occupied':''}${id===selected&&id?' selected':''}`;b.dataset.seat=i;b.style.left=pos.x+'%';b.style.top=pos.y+'%';b.setAttribute('aria-label',`Desk ${i+1}: ${person?person.label:'empty'}`);const num=document.createElement('span'),label=document.createElement('span');num.className='desk-number';num.textContent=String(i+1).padStart(2,'0');label.className='desk-name';label.textContent=person?person.label:'+';b.append(num,label);b.draggable=Boolean(id);b.addEventListener('click',()=>{if(skipClick){skipClick=false;return}deskClick(i)});b.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&id){e.preventDefault();remove(id)}if(e.key==='Escape')clearSelection()});b.addEventListener('dragstart',e=>{if(!id)return e.preventDefault();dragged=id;e.dataTransfer.setData('text/plain',id);e.dataTransfer.effectAllowed='move'});b.addEventListener('dragend',endDrag);b.addEventListener('dragover',e=>{if(dragged){e.preventDefault();e.dataTransfer.dropEffect='move'}});b.addEventListener('dragenter',()=>b.classList.add('drop-target'));b.addEventListener('dragleave',()=>b.classList.remove('drop-target'));b.addEventListener('drop',e=>{e.preventDefault();if(dragged)put(dragged,i);endDrag()});if(id)setupTouch(b,id);root.append(b)})}
function renderRoster(){const root=$('roster'),text=$('search').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(),all=$('showAll').checked;root.replaceChildren();const visible=GROUPS[group].filter(s=>{const name=s.label.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return name.includes(text)&&(all||seat(s.id)<0)});visible.forEach(s=>{const index=seat(s.id),b=document.createElement('button');b.type='button';b.className=`student${index>=0?' seated':''}${selected===s.id?' selected':''}`;b.draggable=true;b.setAttribute('aria-pressed',String(selected===s.id));const avatar=document.createElement('span'),name=document.createElement('span'),where=document.createElement('span');avatar.className='avatar';avatar.textContent=s.name.split(' ').slice(0,2).map(n=>n[0]).join('').toUpperCase();name.className='student-name';name.textContent=s.label;where.className='student-where';where.textContent=index<0?'↗':'#'+(index+1);b.append(avatar,name,where);b.addEventListener('click',()=>{if(skipClick){skipClick=false;return}selected=selected===s.id?null:s.id;render()});b.addEventListener('dragstart',e=>{dragged=s.id;e.dataTransfer.setData('text/plain',s.id);e.dataTransfer.effectAllowed='move'});b.addEventListener('dragend',endDrag);setupTouch(b,s.id);root.append(b)});if(!visible.length){const p=document.createElement('p');p.className='empty-note';p.textContent=text?'No matching students.':'Everyone has a seat. Select “Show seated students too” to move someone.';root.append(p)}}
function render(){$('roomGroup').textContent=group;$('placedCount').textContent=plans[group].filter(Boolean).length;$('totalCount').textContent=GROUPS[group].length;$('waitingCount').textContent=(GROUPS[group].length-plans[group].filter(Boolean).length)+' left';$('selectionHint').textContent=selected?`${student(selected)?.label} selected. Choose a desk or press Escape.`:'Select a student to assign them by tapping a desk.';document.querySelectorAll('.group').forEach(b=>{const active=b.dataset.group===group;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});renderDesks();renderRoster()}
document.querySelectorAll('.group').forEach(b=>b.addEventListener('click',()=>{group=b.dataset.group;selected=null;$('search').value='';$('showAll').checked=false;render()}));$('search').addEventListener('input',render);$('showAll').addEventListener('change',render);$('clearSelectionBtn').addEventListener('click',clearSelection);$('clearBtn').addEventListener('click',()=>{if(!confirm(`Remove all seating assignments for ${group}? Other groups are unaffected.`))return;plans[group]=Array(20).fill(null);selected=null;save();render();toast(`${group} cleared.`)});$('printBtn').addEventListener('click',()=>window.print());$('exportBtn').addEventListener('click',()=>{const file={app:'GLM Grade 9 Seating Studio',version:1,exportedAt:new Date().toISOString(),seats:plans},url=URL.createObjectURL(new Blob([JSON.stringify(file,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='grade9-seating-backup.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);toast('Backup exported. Keep it in approved school storage.')});$('importBtn').addEventListener('click',()=>$('importInput').click());$('importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw Error('File too large.');const data=JSON.parse(await file.text());if(data.version!==1)throw Error('Unsupported backup version.');const incoming=validate(data);if(!confirm('Replace the saved seating plans for all three groups?'))return;plans=incoming;selected=null;save();render();toast('Backup restored.')}catch(error){toast('Import failed: '+error.message)}finally{$('importInput').value=''}});$('roster').addEventListener('dragover',e=>{if(dragged&&seat(dragged)>=0)e.preventDefault()});$('roster').addEventListener('drop',e=>{e.preventDefault();if(dragged&&seat(dragged)>=0)remove(dragged);endDrag()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected)clearSelection()});render();